### PR TITLE
name functions in .init_array and .fini_array

### PR DESCRIPTION
**Pull request by matthw**
automatically rename functions in .init_array and .fini_array to _INIT_X and _FINI_X to make them easier to identify and triage

### CODE REVIEW

**Comment by matthw** [comment]
did the same for .ctors and .dtors

**Comment by xusheng6** [comment]
Thanks for the PR! I have merged it

**Comment by xusheng6** [comment]
I noticed an issue with it. I put the code temporarily on branch elf_init_funcs, and will resolve it after some internal discussion

**Comment by xusheng6** [comment]
Update on this: we have recently moved the view submodules into the API repo (https://github.com/Vector35/binaryninja-api/tree/dev/view/elf), and repos like this is no longer used. I have moved the code https://github.com/Vector35/binaryninja-api/tree/test_elf_init_funcs, and the PR is tracked internally

**Pull request merged**
